name: Inform Telegram

on:
  schedule:
    - cron: '30 14 * * *'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@master

      - name: Install dependencies
        run: |
          R -e 'install.packages("tidyverse")'
          R -e 'install.packages("utils")'
          R -e 'install.packages("telegram.bot")'
          R -e 'install.packages("glue")'
          R -e 'install.packages("pacman")'

      - name: Run R script
        env:
          R_TELEGRAM_BOT_CAETANO: ${{ secrets.R_TELEGRAM_BOT_CAETANO }}
        run: |
          Rscript 'caetano_app_simple.R'
